# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='post/memo/%Y/%m/%d'),
        ),
    ]
